import React from 'react';
import PropTypes from 'prop-types';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import LayoutWrapper from './components/LayoutWrapper';
import ClientWrapper from './components/ClientWrapper';
import { ToastContainer } from 'react-toastify';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata = {
    title: 'ReCompute',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <ClientWrapper>
                    <LayoutWrapper>{children}</LayoutWrapper>
                </ClientWrapper>
                <ToastContainer position="top-right" autoClose={3000} />
            </body>
        </html>
    );
}

RootLayout.propTypes = {
    children: PropTypes.node,
};
